apps/about/urls.py
# app/about/urls.py

# Django modules
from django.urls import path

# Local
from about import views

app_name = 'about'

urlpatterns = [
    path('about/', views.about, name='about'),
]

apps/agents/urls.py
# app/agents/urls.py

# Django modules
from django.urls import path

# Local
from agents import views

app_name = 'agents'

urlpatterns = [
    path('agents/', views.agents, name='agents'),
]

apps/contact/urls.py
# app/contact/urls.py

# Django modules
from django.urls import path

# Local
from contact import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.contact, name='contact'),
]

apps/home/urls.py
# app/home/urls.py

# Django modules
from django.urls import path

# Local
from home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

apps/properties/urls.py
# app/properties/urls.py

# Django modules
from django.urls import path

# Local
from properties import views

app_name = 'properties'

urlpatterns = [
    path('properties/', views.properties, name='properties'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # home
    path('', include('home.urls', namespace='home')),
    # properties
    path('', include('properties.urls', namespace='properties')),
    # agents
    path('', include('agents.urls', namespace='agents')),
    # about
    path('', include('about.urls', namespace='about')),
    # contact
    path('', include('contact.urls', namespace='contact')),
]

apps/about/models.py
from django.db import models

# Create your models here.

apps/agents/models.py
from django.db import models

# Create your models here.

apps/contact/models.py
from django.db import models

# Create your models here.

apps/home/models.py
from django.db import models

# Create your models here.

apps/properties/models.py
from django.db import models

# Create your models here.

apps/users/models.py
from django.db import models

# Create your models here.

apps/about/views.py
# app/about/views.py

# Django modules
from django.shortcuts import render

# Local
from django.http import HttpResponse

# Create your views here.

def about(request):
    return render(request, 'about/about.html')

apps/agents/views.py
# app/agents/views.py

# Django modules
from django.shortcuts import render

# Local
from django.http import HttpResponse

# Create your views here.

def agents(request):
    return render(request, 'agents/agents.html')

apps/contact/views.py
# app/contact/views.py

# Django modules
from django.shortcuts import render

# Local
from django.http import HttpResponse

# Create your views here.

def contact(request):
    return render(request, 'contact/contact.html')

apps/home/views.py
# app/home/views.py

# Django modules
from django.shortcuts import render

# Local
from django.http import HttpResponse

# Create your views here.

def home(request):
    return render(request, 'home/index.html')

apps/properties/views.py
# app/properties/views.py

# Django modules
from django.shortcuts import render

# Local
from django.http import HttpResponse

# Create your views here.

def properties(request):
    return render(request, 'properties/properties.html')

apps/users/views.py
from django.shortcuts import render

# Create your views here.

templates/_partials/explore-our-neighborhoods.html
{% load static %}

  <section class="probootstrap-section">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Explore Our Neighborhoods</h2>
      </div>
      <div class="row probootstrap-gutter10">
        <div class="col-md-6 col-sm-6">
          <a href="#" class="probootstrap-hover-overlay">
            <img src="{% static 'assets/img/slider_2.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>New York</h3>
              <p>430 Properties</p>
            </div>
          </a>
        </div>
        <div class="col-md-6 col-sm-6">
          <a href="#" class="probootstrap-hover-overlay">
            <img src="{% static 'assets/img/slider_1.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>San Francisco</h3>
              <p>294 Properties</p>
            </div>
          </a>
        </div>
        <div class="clearfix visible-sm-block"></div>

        <div class="col-md-4 col-sm-6">
          <a href="#" class="probootstrap-hover-overlay">
            <img src="{% static 'assets/img/slider_3.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>Brooklyn</h3>
              <p>300 Properties</p>
            </div>
          </a>
        </div>
        <div class="col-md-4 col-sm-6">
          <a href="#" class="probootstrap-hover-overlay">
            <img src="{% static 'assets/img/slider_4.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>Chicago</h3>
              <p>268 Properties</p>
            </div>
          </a>
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-4 col-sm-6">
          <a href="#" class="probootstrap-hover-overlay">
            <img src="{% static 'assets/img/slider_2.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
            <div class="probootstrap-text-overlay">
              <h3>Los Angeles</h3>
              <p>342 Properties</p>
            </div>
          </a>
        </div>

      </div>
    </div>
  </section>

templates/_partials/featured-listing.html
{% load static %}

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Featured Listing</h2>
      </div>
      <div class="row">
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_1.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ 1,121,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_2.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ 250,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_3.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-rent"><span>for rent</span></div>
              <div class="probootstrap-listing-price"><strong>$ 60,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_4.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ 125,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        <div class="clearfix visible-sm-block"></div>
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_2.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ 125,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
        <div class="col-md-4 col-sm-6">
          <div class="probootstrap-card probootstrap-listing">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/slider_1.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
              <a href="#" class="probootstrap-love"><i class="icon-heart"></i></a>
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading"><a href="#">3 Bed Room Property for Sale</a></h2>
              <div class="probootstrap-listing-location">
                <i class="icon-location2"></i> <span>360 W Wellington Chicago, IL 60657</span>
              </div>
              <div class="probootstrap-listing-category for-sale"><span>for sale</span></div>
              <div class="probootstrap-listing-price"><strong>$ 125,000</strong> / month</div>
            </div>
            <div class="probootstrap-card-extra">
              <ul>
                <li>
                  Area
                  <span>2400 m2</span>
                </li>
                <li>
                  Beds
                  <span>3</span>
                </li>
                <li>
                  Baths
                  <span>2</span>
                </li>
                <li>
                  Garages
                  <span>1</span>
                </li>
              </ul>
            </div>
          </div>
          <!-- END listing -->
        </div>
      </div>
    </div>
  </section>

templates/_partials/our-agents.html
{% load static %}

  <section class="probootstrap-section probootstrap-section-lighter">
    <div class="container">
      <div class="row heading">
        <h2 class="mt0 mb50 text-center">Our Agents</h2>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_1.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Jeremy Slater</h2>
              <p><small>Real Estate Brooker</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_2.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">James Butterly</h2>
              <p><small>Buying Agent</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_3.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">James Smith</h2>
              <p><small>Real Estate Brooker</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_4.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Chris White</h2>
              <p><small>Selling Agent</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>

        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_3.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">James Smith</h2>
              <p><small>Real Estate Brooker</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_4.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Chris White</h2>
              <p><small>Selling Agent</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_1.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">Jeremy Slater</h2>
              <p><small>Real Estate Brooker</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-6">
          <div class="probootstrap-card probootstrap-person text-left">
            <div class="probootstrap-card-media">
              <img src="{% static 'assets/img/person_2.jpg' %}" class="img-responsive" alt="Free HTML5 Template by uicookies.com">
            </div>
            <div class="probootstrap-card-text">
              <h2 class="probootstrap-card-heading mb0">James Butterly</h2>
              <p><small>Buying Agent</small></p>
              <p><a href="#">View Details</a></p>
            </div>
          </div>
        </div>


      </div>
    </div>
  </section>

templates/_partials/why-choose-us.html
{% load static %}

  <section class="probootstrap-half reverse">
    <div class="image-wrap">
      <div class="image" style="background-image: url({% static 'assets/img/slider_5.jpg' %});"></div>
    </div>
    <div class="text">
      <p class="mb10 subtitle">Why Choose Us</p>
      <h3 class="mt0 mb40">You Will Love Our Services</h3>
      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.</p>
      <p class="mb50">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
      <p><a href="#" class="btn btn-primary mb10">Find out more</a></p>
    </div>
  </section>

templates/agents/agents.html
<!-- templates/agents/agents.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }} Agents
{% endblock title %}

{% block content %}
  <!-- START: breadcrumb -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Agents</span>
              </div>
              <h1>Agents</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({% static 'assets/img/slider_1.jpg' %});"></li>
      <li style="background-image: url({% static 'assets/img/slider_4.jpg' %});"></li>
      <li style="background-image: url({% static 'assets/img/slider_2.jpg' %});"></li>
    </ul>
  </section>
  <!-- END: breadcrumb -->
  
  <!-- START: Our Agents -->
  {% include '_partials/our-agents.html' %}
  <!-- END: Our Agents -->

  <!-- START: Why Choose Us -->
  {% include '_partials/why-choose-us.html' %}
  <!-- END: Why Choose Us -->

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Hotel Booking :: {% endblock title %}</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'assets/css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  <meta name="robots" content="noindex, nofollow">
  </head>
  <body>

  <!-- START: header -->
  <div class="probootstrap-loader"></div>
  <header role="banner" class="probootstrap-header">
    <div class="container">
        <a href="/" class="probootstrap-logo">Haus<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li class="{% if request.path == '/' %}active{% endif %}">
              <a href="{% url 'home:home' %}">Home</a>
            </li>
            <li class="{% if request.path == '/properties/' %}active{% endif %}">
              <a href="{% url 'properties:properties' %}">Properties</a>
            </li>
            <li class="{% if request.path == '/agents/' %}active{% endif %}">
              <a href="{% url 'agents:agents' %}">Agents</a>
            </li>
            <li class="{% if request.path == '/about/' %}active{% endif %}">
              <a href="{% url 'about:about' %}">About</a>
            </li>
            <li class="{% if request.path == '/contact/' %}active{% endif %}">
              <a href="{% url 'contact:contact' %}">Contact</a>
            </li>
          </ul>
          <div class="extra-text visible-xs"> 
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Address</h5>
            <p>198 West 21th Street, Suite 721 New York NY 10016</p>
            <h5>Connect</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook2"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </nav>
    </div>
  </header>
  <!-- END: header -->

  {% block content %}
  {% endblock content %}

  <!-- START: footer -->
  <footer class="probootstrap-footer probootstrap-bg" style="background-image: url({% static 'assets/img/slider_3.jpg)">
    <div class="container">
      <div class="row mb60">
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">About Haus.</h4>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
            <p><a href="#">Read more...</a></p>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Quick Links</h4>
            <ul class="stack-link">
              <li><a href="#">Property Listing</a></li>
              <li><a href="#">Rent Properties</a></li>
              <li><a href="#">Sell Properties</a></li>
              <li><a href="#">Agents</a></li>
              <li><a href="#">Testimonial</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget">
            <h4 class="heading">Popular Cities</h4>
            <ul class="stack-link">
              <li><a href="#">New York <small>(320 properties)</small></a></li>
              <li><a href="#">San Francisco <small>(294 properties)</small></a></li>
              <li><a href="#">Brooklyn <small>(300 properties)</small></a></li>
              <li><a href="#">Chicago <small>(268 properties)</small></a></li>
              <li><a href="#">Los Angeles <small>(342 properties)</small></a></li>
            </ul>
          </div> 
        </div>
        <div class="col-md-3">
          <div class="probootstrap-footer-widget probootstrap-link-wrap">
            <h4 class="heading">Subscribe</h4>
            <p>Far far away behind the word mountains far from.</p>
            <form action="#">
              <div class="form-field">
                <input type="text" class="form-control" placeholder="Enter your email">
                <button class="btn btn-subscribe">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="row copyright">
        <div class="col-md-6">
          <div class="probootstrap-footer-widget">
            <p>&copy; 2017 <a href="https://uicookies.com/">uiCookies:Haus</a>. Designed by <a href="https://uicookies.com/">uicookies.com</a> <br> Demo Photos from <a href="https://pixabay.com/">Pixabay</a> &amp; <a href="https://unsplash.com/">Unsplash</a></p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="probootstrap-footer-widget right">
            <ul class="probootstrap-footer-social">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- END: footer -->

  <!-- START: scripts -->
  <div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="icon-chevron-thin-up"></i></a>
  </div>

  <script src="{% static 'assets/js/scripts.min.js' %}"></script>
  <script src="{% static 'assets/js/main.min.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>

  <script defer src="https://static.cloudflareinsights.com/beacon.min.js/vcd15cbe7772f49c399c6a5babf22c1241717689176015" integrity="sha512-ZpsOmlRQV6y907TI0dKBHq9Md29nnaEIPlkf84rnaERnq6zvWvPUqr2ft8M1aS28oN72PdrCzSjY4U6VaAw1EQ==" data-cf-beacon='{"rayId":"954d72a78a102c14","version":"2025.6.2","r":1,"token":"1aea4905526a46c1a4fc9bc1d0e89a42","serverTiming":{"name":{"cfExtPri":true,"cfEdge":true,"cfOrigin":true,"cfL4":true,"cfSpeedBrain":true,"cfCacheStatus":true}}}' crossorigin="anonymous"></script>
  <!-- END: scripts -->

</body>
</html>

templates/properties/properties.html
<!-- templates/properties/properties.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ block.super }} Properties
{% endblock title %}

{% block content %}

  <!-- START: breadcrumb -->
  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="#">Home</a><span>Properties</span>
              </div>
              <h1>Properties</h1>
            </div>

          </div>
        </div>
      </div>
    </div>
    <ul class="slides">
      <li style="background-image: url({% static 'assets/img/slider_1.jpg' %});"></li>
      <li style="background-image: url({% static 'assets/img/slider_4.jpg' %});"></li>
      <li style="background-image: url({% static 'assets/img/slider_2.jpg' %});"></li>
    </ul>
  </section>
  <!-- END: breadcrumb  -->

  <!-- START: Featured listing -->
  {% include '_partials/featured-listing.html' %}
  <!-- END: Featured listing  -->

  <!-- START: Explore Our Neighborhoods -->
  {% include '_partials/explore-our-neighborhoods.html' %}
  <!-- END: Explore Our Neighborhoods -->

  <!-- START: Why Choose Us -->
  {% include '_partials/why-choose-us.html' %}
  <!-- END: Why Choose Us  -->

{% endblock content %}